### ISSUE TITLE
Railsを動かすのに必要なgemが色々足りていない

### ISSUE THREAD

**Issue by Tamatebako0205** [maho-na510/rubyPractice#4]
# 概要
Railsを動かすのに必要なgemが色々足りておらず起動できない
RailsはRailsだけで上げるものではなくpumaやbootsnapといったパーツが必要になってきます

# 改善
Railsに必要なgemを調査してGemfileに追記してbuildする(Railsチュートリアルとか、そこらへん参考にお願いします)

```
source 'https://rubygems.org'
gem 'rails', '~> 7.0.2'
gem 'bootsnap'
gem 'puma'
...
```

**Comment by Kashiwara0205** [comment]
mainブランチで実行してしまった為一旦クローズ
